version: '3.9'
services:
  prod-db1:
    image: postgres:15
    container_name: prod-db1
    environment:
      POSTGRES_DB: prod1
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - prod1_data:/var/lib/postgresql/data
      - ./prod1_postgresql.conf:/etc/postgresql/postgresql.conf
    command: ["postgres", "-c", "config_file=/etc/postgresql/postgresql.conf"]
    networks:
      - prod-network

  prod-db2:
    image: postgres:15
    container_name: prod-db2
    environment:
      POSTGRES_DB: prod2
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
    ports:
      - "5433:5432"
    volumes:
      - prod2_data:/var/lib/postgresql/data
      - ./init_db2.sh:/docker-entrypoint-initdb.d/init_db2.sh
    networks:
      - prod-network


networks:
  prod-network:
    driver: bridge

volumes:
  prod1_data:
  prod2_data:

